version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo_test
    restart: unless-stopped
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example